<?php

declare(strict_types=1);

namespace Apkk\LaravelErrorMonitor\Services;

use Apkk\LaravelErrorMonitor\Contracts\LogNormalizer;

/**
 * Conservative message normalizer.
 *
 * Only values that are known to vary between two occurrences of the *same*
 * failure are replaced: identifiers, timestamps, query strings, temporary paths
 * and framework generated file names.
 *
 * Values that identify the failure are deliberately left alone, because
 * replacing them would merge unrelated failures: HTTP statuses, PHP error
 * numbers, SQLSTATE and driver error codes, line numbers, version numbers,
 * amounts and quantities. Bare integers are therefore only replaced when the
 * surrounding text marks them as a record id.
 */
final class DefaultLogNormalizer implements LogNormalizer
{
    public function normalize(string $message): string
    {
        $patterns = [
            '/\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/i' => '{uuid}',
            '/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i' => '{email}',
            '/\b\d{4}-\d{2}-\d{2}[T\s]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?\b/' => '{datetime}',
            '/\b\d{4}\/\d{2}\/\d{2}\s+\d{2}:\d{2}:\d{2}\b/' => '{datetime}',
            '/(?<![\w:])(?:\d{1,3}\.){3}\d{1,3}(?![\w.])/' => '{ip}',
            '/(?<![\w:])(?:[0-9a-f]{1,4}:){3,7}[0-9a-f]{1,4}(?![\w:])/i' => '{ip}',
            '#(?:https?://[^\s?"\']+|/[A-Za-z0-9._~/%-]+)\?[^\s"\']+#i' => static fn (array $match): string => preg_replace('/\?.*/', '?{query}', $match[0]) ?? $match[0],
            '#(?:/tmp|/private/tmp|/var/folders/[^/]+/[^/]+/T)/[^\s"\']+#' => '{tmp_path}',
            '#/bootstrap/cache/(?:config|events|packages|services|routes(?:-[A-Za-z0-9]+)?)\.php#' => '/bootstrap/cache/{generated}.php',
            // Blade views, cached data and file sessions generated by the framework.
            '#(framework/views/)[A-Za-z0-9_-]+(\.php)#' => '$1{generated}$2',
            '#(framework/cache/data/)[A-Za-z0-9/_-]+#' => '$1{generated}',
            '#(framework/sessions/)[A-Za-z0-9_-]+#' => '$1{generated}',
            '#\bCompiled view [A-Za-z0-9_-]+\.php#' => 'Compiled view {generated}.php',
            // Digests and other long random values, e.g. session identifiers.
            '/\b[0-9a-f]{32,64}\b/i' => '{hash}',
            '/\b(?=[A-Za-z0-9]*\d)(?=[A-Za-z0-9]*[A-Za-z])[A-Za-z0-9]{24,}\b/' => '{random}',
            '/\b((?:[A-Za-z_][A-Za-z0-9_]*[_-])?(?:id|uuid))\s*([=:]|\#)?\s*\d+\b/i' => '$1$2{id}',
            '#/([A-Za-z][A-Za-z0-9_-]*)/\d+(?=(?:/|\b))#' => '/$1/{id}',
        ];

        foreach ($patterns as $pattern => $replacement) {
            $message = (string) preg_replace_callback(
                $pattern,
                is_callable($replacement) ? $replacement : static fn (array $match): string => (string) preg_replace($pattern, $replacement, $match[0]),
                $message,
            );
        }

        return trim((string) preg_replace('/\s+/', ' ', $message));
    }

    public function normalizeRoute(?string $route): ?string
    {
        if ($route === null || trim($route) === '') {
            return null;
        }

        $route = trim($route);

        // Drop scheme and host so the same route on two hosts stays one route.
        $route = (string) preg_replace('#^[a-z][a-z0-9+.-]*://[^/]+#i', '', $route);

        // Drop the query string and the fragment.
        $route = (string) preg_replace('/[?#].*$/', '', $route);

        // Route parameters are already placeholders; unify their spelling.
        $route = (string) preg_replace('/\{[^}]*\}/', '{param}', $route);

        $route = (string) preg_replace(
            '/(?<=\/)[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}(?=\/|$)/i',
            '{uuid}',
            $route,
        );

        $route = (string) preg_replace('/(?<=\/)\d+(?=\/|$)/', '{id}', $route);
        $route = (string) preg_replace('#/{2,}#', '/', $route);
        $route = rtrim($route, '/');

        if ($route === '') {
            return '/';
        }

        return str_starts_with($route, '/') ? $route : '/'.$route;
    }
}
